### ISSUE TITLE
oAuth 2.0

### ISSUE THREAD

**Issue by phipps73** [XeroAPI/Xero-CFML#9]
Xero are deprecating OAuth 1.0a and switching to oAuth 2.0. Are there any plans to update this SDK to support oAuth 2.0? Looks like it could use this: https://github.com/coldfumonkeh/oauth2/blob/master/xero.cfc as a starting point?

**Comment by SidneyAllen** [comment]
@phipps73 - yeah we'd love to offer an official CFML SDK, but have not had the bandwidth.  It will require creating code templates from scratch so we can generate the library using our OpenAPI specifications (this is how all our OAuth 2 SDKs are being built now.  In the meantime, I concur with your recommendation to use an OAuth 2 library to authenticate and make secure API calls.

**Comment by phipps73** [comment]
@SidneyAllen - thanks. I have had a brief attempt at working with the new oAuth 2.0 Xero API and unfortunately it isn't going to work for our needs at the moment. We currently use the private app setup with oAuth 1.0 of the API and only link directly to our own Xero account - we use it to create a billing contact in our Xero account using the primary contact in our database. As we do this infrequently having to re-auth via the oAuth 2.0 process every time we want to update a contact or query the Invoices endpoint is a showstopper for us. Looking at the Xero developer forums it seems it is a common complaint of the new API where the Private App was their only use of the API.

**Comment by SidneyAllen** [comment]
@phipps73 - Hey Dave,

Yeah the topic of deprecation of the private app type has been a hot topic with developers.  If you can join our webinar next week, we will be sharing an update on that.

Sign up for our developer webinar - In conversation with the Xero developer platform. It's your chance to hear from and ask questions to the Xero teams building the developer platform you innovate with today. Join us on Tuesday 17th November at 11am NZT.

https://xero.zoom.us/webinar/register/2916031589950/WN_pQJMjMRST7ShNGroxMImfw
